name: Taxonomy build, Ping Integration
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: jenv_taxonomy_2024

jobs:
  build_and_ping:
    runs-on: ubuntu-latest
    name: Build Taxonomy package
    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p build
      - run: |
          sudo apt install zip
      - run: |
          zip -r ./build/${{ env.TAX_NAME }} ${{ env.TAX_NAME }}

      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: ${{ env.TAX_NAME }}-artifact
          path: build/${{ env.TAX_NAME }}.zip

      - name: Ping Integration
        env:
          archive_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}
        run: |
          type="trigger-workflow"

          curl -L \
            -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sbr-nl/cicd/actions/workflows/integration.yaml/dispatches \
          -d '{"ref":"${{ github.ref }}", "inputs": {"branch": "${{ github.ref_name }}", "repository": "${{ github.repository }}", "taxonomy_name": "${{ env.TAX_NAME }}", "message": "Ping! " }}'
